config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index'
  post '/calculate', to: 'welcome#calculate', as: :calculate

end

app/models/calculator.rb
class Calculator
  @@ops = {
    1 => { '*' => :mult, '/' => :div },
    0 => { '+' => :add, '-' => :sub }
  }

  def initialize str
    @str = str
  end

  def calculate
    return 'err' unless valid?

    arr = @str.split /([+\-*\/])/
    1.downto(0) do |pr|
      arr.each_with_index do |val, i|
        if @@ops[pr].keys.include? val
          arr[i+1] = send @@ops[pr][val], arr[i-1].to_f, arr[i+1].to_f
          arr[i-1], arr[i] = nil
        end
      end
      arr.reject! { |c| c.nil? }
    end
    res = arr.first
    res = res.to_i if res == res.to_i
    return res
  end

  private

  def valid?
    not (@str =~ /^\s*-?(\d+|[0-9]*[.][0-9]+)(?:\s*[-+*\/]\s*(\d+|[0-9]*[.][0-9]+))+$/).nil?
  end

  def mult a, b
    a * b
  end

  def div a, b
    a / b
  end

  def add a, b
    a + b
  end

  def sub a, b
    a - b
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

  def calculate
    calc = Calculator.new params[:exp]
    @result = calc.calculate
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Calc
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/welcome/index.html.haml
:javascript
  window.calc_path = "#{calculate_path}";

#calculator
  .top
    %span.clear C
    .screen
  .keys
    %span 7
    %span 8
    %span 9
    %span.operator +
    %span 4
    %span 5
    %span 6
    %span.operator -
    %span 1
    %span 2
    %span 3
    %span.operator /
    %span 0
    %span .
    %span.eval =
    %span.operator *